language: python

python:
    - "3.4"
 
sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - libboost-test-dev

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy cython setuptools
    - wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz
    - tar xzf 3.3.4.tar.gz
    - rm 3.3.4.tar.gz
    - mv eigen-eigen-5a0156e40feb/Eigen .

script:
    - export CC=/usr/bin/gcc-4.9
    - export CXX=/usr/bin/g++-4.9
    - git clone --depth 1 https://github.com/marekpetrik/CRAAM.git
    - cd CRAAM
    - mv ../Eigen .
    - cd python 
    - python3 setup.py install
    - cd ..
    - cd ..
    - python3 setup.py install 
    - mkdir test_dir
    - cd test_dir
    - python3 -mraam.test
